#!/usr/bin/env node
// LUDIARS infisical — 各 LUDIARS サービスの env-cli (Infisical) 操作を一括実行。
//
// Usage:
//   node scripts/infisical.mjs <op> <id...> [--all]
//   node scripts/infisical.mjs get <key> <id...>
//   node scripts/infisical.mjs set <key=value> <id...>
//   node scripts/infisical.mjs setup-batch (--all | <id...>) [--force]
//   node scripts/infisical.mjs setup-batch --init
//
// op:
//   setup            対話形式で 1 サービスの Infisical 設定
//   setup-batch      .infisical-batch.json から shared credentials + per-service projectId
//                    を読んで全サービスの .env.secrets を非対話で生成
//   test             接続テスト
//   gen              .env 生成
//   initialize       デフォルト値を Infisical に登録 + 続けて gen も実行 (= .env も生成)。
//                    単独 env-cli の initialize は Infisical 登録だけだが、 この wrapper は
//                    LUDIARS 一括 bootstrap でよく使う流れに合わせて gen を連結する。
//   cernere-register Cernere admin で login → 各サービスを managed_project として WS で register
//                    → 返却された clientId/secret を各サービスの .env に idempotent 書出
//                    (marker でブロック管理、 重複定義は自動統合)。
//                    .infisical-batch.json の cernere.{url,adminEmail,adminPassword} を使う。
//   list / get / set
//
// 通常の op は <repoDir>/<subDir?> で `npm run env:<op>` を直列実行。
// setup-batch は npm script ではなく .env.secrets を直接書く。
//
// 関連:
//   - scripts/services.mjs            サービス registry (PORT-MAP と同期)
//   - LUDIARS/.infisical-batch.json   shared credentials + per-service projectId (gitignored)
//   - ../Cernere/packages/env-cli     env-cli の本体

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SERVICES, findService, resolveIds } from './services.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BATCH_CONFIG_PATH = '.infisical-batch.json';

const VALID_OPS = ['setup', 'setup-batch', 'test', 'gen', 'list', 'get', 'set', 'initialize', 'cernere-register'];

function printUsage() {
  console.log(`Usage:
  node scripts/infisical.mjs <op> <id...> [--all]
  node scripts/infisical.mjs get <key> <id...>
  node scripts/infisical.mjs set <key=value> <id...>
  node scripts/infisical.mjs setup-batch (--all | <id...>) [--force]
  node scripts/infisical.mjs setup-batch --init
  node scripts/infisical.mjs cernere-register (--all | <id...>)

op: ${VALID_OPS.join(' | ')}

Options:
  --all      env-cli を持つ全 service を対象 (hasEnvCli=true)
  --init     setup-batch のテンプレ ${BATCH_CONFIG_PATH} を書き出す
  --force    setup-batch: 既存 .env.secrets を上書き
  --help     これを表示

例:
  node scripts/infisical.mjs setup-batch --init
  node scripts/infisical.mjs setup-batch --all
  node scripts/infisical.mjs gen bibliotheca aedilis
  node scripts/infisical.mjs initialize --all

setup-batch:
  ${BATCH_CONFIG_PATH} (gitignored、 LUDIARS repo root) に shared credentials +
  per-service projectId を記述し、 各サービスの .env.secrets を非対話で生成する。
  ProjectID はサービス毎に違うが clientId/clientSecret は通常 1 つの machine
  identity を共有する想定 (defaults でまとめて、 サービス側で override 可)。

他の op は ../Cernere/packages/env-cli (各サービスが \`npm run env:<op>\` で呼ぶ)
の wrapper。`);
}

// ── setup-batch 用 ────────────────────────────────────────────

function loadBatchConfig() {
  const p = resolve(ROOT, BATCH_CONFIG_PATH);
  if (!existsSync(p)) {
    console.error(`${BATCH_CONFIG_PATH} が見つかりません。 先に setup-batch --init を実行してください`);
    process.exit(1);
  }
  try {
    const parsed = JSON.parse(readFileSync(p, 'utf-8'));
    if (typeof parsed !== 'object' || !parsed.services) {
      throw new Error('services が無い');
    }
    return parsed;
  } catch (e) {
    console.error(`${BATCH_CONFIG_PATH} の parse に失敗: ${e.message}`);
    process.exit(1);
  }
}

function writeBatchTemplate() {
  const p = resolve(ROOT, BATCH_CONFIG_PATH);
  if (existsSync(p)) {
    console.error(`${BATCH_CONFIG_PATH} は既に存在します — 上書きしません`);
    process.exit(1);
  }
  /** @type {Record<string, { projectId: string }>} */
  const services = {};
  for (const s of SERVICES) {
    if (!s.hasEnvCli) continue;
    services[s.id] = { projectId: '<your-infisical-project-id>' };
  }
  const tpl = {
    defaults: {
      siteUrl: 'https://app.infisical.com',
      environment: 'dev',
      clientId: '<shared-universal-auth-client-id>',
      clientSecret: '<shared-universal-auth-client-secret>',
    },
    services,
    cernere: {
      url: 'http://localhost:8080',
      adminEmail: '<cernere-system-admin-email>',
      adminPassword: '<cernere-system-admin-password>',
    },
  };
  writeFileSync(p, JSON.stringify(tpl, null, 2) + '\n', 'utf-8');
  console.log(`テンプレを生成しました: ${p}`);
  console.log('編集して各サービスの projectId と shared credentials を埋めてください。');
  console.log(`(${BATCH_CONFIG_PATH} は .gitignore 済 — commit されません)`);
}

function formatEnvSecrets(svc) {
  return [
    `# Infisical bootstrap (generated by LUDIARS scripts/infisical.mjs setup-batch)`,
    `INFISICAL_SITE_URL=${svc.siteUrl}`,
    `INFISICAL_PROJECT_ID=${svc.projectId}`,
    `INFISICAL_ENVIRONMENT=${svc.environment}`,
    `INFISICAL_CLIENT_ID=${svc.clientId}`,
    `INFISICAL_CLIENT_SECRET=${svc.clientSecret}`,
    ``,
  ].join('\n');
}

function runSetupBatch(rest) {
  if (rest.includes('--init')) {
    writeBatchTemplate();
    return;
  }
  const force = rest.includes('--force');
  const cfg = loadBatchConfig();
  const d = cfg.defaults ?? {};

  const { ids, unknown } = resolveIds(rest, { requireEnvCli: rest.includes('--all') });
  if (unknown.length) {
    console.error(`unknown service IDs: ${unknown.join(', ')}`);
    process.exit(2);
  }
  if (!ids.length) {
    console.error('対象サービスがありません。 <id...> か --all を指定してください');
    process.exit(2);
  }

  let written = 0;
  let skipped = 0;
  for (const id of ids) {
    const spec = findService(id);
    if (!spec || !spec.hasEnvCli) {
      console.warn(`[${id}] hasEnvCli=false — skip`);
      skipped++;
      continue;
    }
    const svcCfg = cfg.services[id];
    if (!svcCfg) {
      console.warn(`[${id}] ${BATCH_CONFIG_PATH} に services.${id} がありません — skip`);
      skipped++;
      continue;
    }
    const resolved = {
      siteUrl:      svcCfg.siteUrl      ?? d.siteUrl      ?? 'https://app.infisical.com',
      environment:  svcCfg.environment  ?? d.environment  ?? 'dev',
      projectId:    svcCfg.projectId,
      clientId:     svcCfg.clientId     ?? d.clientId,
      clientSecret: svcCfg.clientSecret ?? d.clientSecret,
    };
    if (!resolved.projectId || !resolved.clientId || !resolved.clientSecret) {
      console.error(`[${id}] projectId / clientId / clientSecret のいずれかが未設定 — skip`);
      skipped++;
      continue;
    }
    const dir = resolve(ROOT, spec.repoDir, spec.subDir ?? '.');
    if (!existsSync(dir)) {
      console.error(`[${id}] repo dir 不在: ${dir} — skip`);
      skipped++;
      continue;
    }
    const target = join(dir, '.env.secrets');
    if (existsSync(target) && !force) {
      console.warn(`[${id}] ${target} は既に存在 — skip (--force で上書き)`);
      skipped++;
      continue;
    }
    writeFileSync(target, formatEnvSecrets(resolved), 'utf-8');
    console.log(`[${id}] ${target} 書込 (projectId=${resolved.projectId.slice(0, 8)}...)`);
    written++;
  }

  console.log(`\n[setup-batch] 完了: 書込=${written}, skip=${skipped}`);
  if (written > 0) {
    console.log('次のステップ: `node scripts/infisical.mjs test --all` で接続確認、 `gen --all` で .env 生成');
  }
}

// ── cernere-register ─────────────────────────────────────────
//
// Cernere の `managed_project.register` は WS dispatch のみ (HTTP REST 経由が
// ない)。 流れは:
//   1. POST /api/auth/login (email + password) → adminAccessToken
//   2. WS /auth?token=<adminAccessToken> 接続
//   3. server から { type: "connected" } 受信
//   4. send { type: "module_request", module: "managed_project", action: "register",
//             payload: { project: {key, name}, user_data: {columns: {}} } }
//   5. recv { type: "module_response", payload: { clientId, clientSecret, ... } }
//   6. clientSecret は **この 1 度しか** 平文で返ってこない (DB は bcrypt hash)
//      → 即 サービスの .env.cernere に書出す
//   7. 既存 active project → "already exists" エラーで skip
//      既存 inactive project → 再登録で reactivate (clientSecret は返らない)

async function adminLogin(cernereUrl, email, password) {
  const res = await fetch(`${cernereUrl}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`admin login failed: ${res.status} ${body}`);
  }
  const data = await res.json();
  if (!data.accessToken) throw new Error('admin login: accessToken が返ってこない');
  return data.accessToken;
}

/**
 * Cernere WS で 1 件の module_request を送って response を待つ。
 * Promise が resolve したら接続は閉じる (短命接続)。
 */
function wsCommand(cernereUrl, accessToken, module_, action, payload) {
  return new Promise((resolveP, rejectP) => {
    const wsUrl = cernereUrl.replace(/^http/, 'ws') + `/auth?token=${accessToken}`;
    if (typeof WebSocket === 'undefined') {
      rejectP(new Error('Node 22+ の native WebSocket が必要です (`node --version`)'));
      return;
    }
    const ws = new WebSocket(wsUrl);
    let settled = false;
    const finish = (err, value) => {
      if (settled) return;
      settled = true;
      try { ws.close(); } catch { /* ignore */ }
      err ? rejectP(err) : resolveP(value);
    };
    const timer = setTimeout(() => finish(new Error('WS timeout (15s)')), 15000);

    ws.addEventListener('open', () => { /* wait for "connected" before send */ });
    ws.addEventListener('error', (e) => finish(new Error(`WS error: ${e?.message ?? e?.error?.message ?? e?.type ?? 'unknown'}`)));
    ws.addEventListener('close', () => {
      clearTimeout(timer);
      if (!settled) finish(new Error('WS closed without response'));
    });
    ws.addEventListener('message', (ev) => {
      let msg;
      try { msg = JSON.parse(typeof ev.data === 'string' ? ev.data : String(ev.data)); }
      catch { return; }
      if (msg.type === 'connected') {
        ws.send(JSON.stringify({ type: 'module_request', module: module_, action, payload }));
        return;
      }
      if (msg.type === 'ping') {
        ws.send(JSON.stringify({ type: 'pong', ts: msg.ts }));
        return;
      }
      if (msg.type === 'module_response' && msg.module === module_ && msg.action === action) {
        clearTimeout(timer);
        finish(null, msg.payload);
        return;
      }
      if (msg.type === 'error') {
        clearTimeout(timer);
        finish(new Error(msg.message ?? 'unknown WS error'));
        return;
      }
    });
  });
}

const CERNERE_KEYS = ['CERNERE_URL', 'CERNERE_PROJECT_CLIENT_ID', 'CERNERE_PROJECT_CLIENT_SECRET'];
const CERNERE_MARKER_BEGIN = '# >>> LUDIARS cernere-register (managed by scripts/infisical.mjs) >>>';
const CERNERE_MARKER_END   = '# <<< LUDIARS cernere-register <<<';

/**
 * CERNERE_URL / CLIENT_ID / CLIENT_SECRET を <repoDir>/.env に idempotent 書込。
 *   - 既存の .env の中で本ツール管理ブロック (marker 内) を全置換
 *   - marker 外で同名キーが書かれていたら警告して remove (重複定義回避)
 * tsx --env-file-if-exists=.env がそのまま load するので サービス側は無改修。
 */
function writeCernereCreds(spec, cernereUrl, clientId, clientSecret) {
  const dir = resolve(ROOT, spec.repoDir, spec.subDir ?? '.');
  const target = join(dir, '.env');

  let original = '';
  if (existsSync(target)) original = readFileSync(target, 'utf-8');

  // 既存の cernere-register ブロックと、 marker 外の同名キーを除去。
  const lines = original.split('\n');
  /** @type {string[]} */
  const kept = [];
  let inBlock = false;
  const warnedKeysOutside = [];
  for (const line of lines) {
    if (line.trim() === CERNERE_MARKER_BEGIN) { inBlock = true; continue; }
    if (line.trim() === CERNERE_MARKER_END)   { inBlock = false; continue; }
    if (inBlock) continue;
    // marker 外で CERNERE_* が手書きされていたら drop して warn
    const m = line.match(/^\s*(CERNERE_URL|CERNERE_PROJECT_CLIENT_ID|CERNERE_PROJECT_CLIENT_SECRET)\s*=/);
    if (m) { warnedKeysOutside.push(m[1]); continue; }
    kept.push(line);
  }
  // 末尾改行を整える
  while (kept.length && kept[kept.length - 1].trim() === '') kept.pop();

  const block = [
    CERNERE_MARKER_BEGIN,
    `# 生成時刻: ${new Date().toISOString()}`,
    `# このブロックは cernere-register が上書きします。 手で書き換えても次回実行で消えます。`,
    `CERNERE_URL=${cernereUrl}`,
    `CERNERE_PROJECT_CLIENT_ID=${clientId}`,
    `CERNERE_PROJECT_CLIENT_SECRET=${clientSecret}`,
    CERNERE_MARKER_END,
  ];
  const content = [...kept, '', ...block, ''].join('\n');
  writeFileSync(target, content, 'utf-8');
  if (warnedKeysOutside.length) {
    console.warn(`[${spec.id}] .env の marker 外で書かれていた ${warnedKeysOutside.join('/')} を統合 (重複定義回避)`);
  }
  return target;
}

async function runCernereRegister(rest) {
  const cfg = loadBatchConfig();
  const ce = cfg.cernere;
  if (!ce || !ce.url || !ce.adminEmail || !ce.adminPassword) {
    console.error(`${BATCH_CONFIG_PATH} に cernere { url, adminEmail, adminPassword } を設定してください`);
    process.exit(1);
  }

  const { ids, unknown } = resolveIds(rest);
  if (unknown.length) {
    console.error(`unknown service IDs: ${unknown.join(', ')}`);
    process.exit(2);
  }
  if (!ids.length) {
    console.error('対象サービスがありません。 <id...> か --all を指定してください');
    process.exit(2);
  }

  console.log(`[cernere-register] admin login -> ${ce.url}`);
  let token;
  try {
    token = await adminLogin(ce.url, ce.adminEmail, ce.adminPassword);
  } catch (e) {
    console.error(`admin login 失敗: ${e.message}`);
    process.exit(1);
  }
  console.log(`[cernere-register] login OK`);

  let registered = 0, skipped = 0, reactivated = 0, failed = 0;
  for (const id of ids) {
    const spec = findService(id);
    if (!spec) continue;
    if (!spec.needsCernere) {
      console.warn(`[${id}] needsCernere=false — skip`);
      skipped++;
      continue;
    }
    const definition = {
      project: { key: spec.id, name: spec.displayName },
      user_data: { columns: {} },
    };
    try {
      const res = await wsCommand(ce.url, token, 'managed_project', 'register', definition);
      if (res?.clientId && res?.clientSecret) {
        const path = writeCernereCreds(spec, ce.url, res.clientId, res.clientSecret);
        console.log(`[${id}] register OK — ${path} に書込 (clientId=${res.clientId.slice(0, 16)}...)`);
        registered++;
      } else if (res?.message?.includes('reactivated')) {
        console.warn(`[${id}] 既存 inactive project を reactivate — 既存 clientSecret は不明、 必要なら手動 rotate`);
        reactivated++;
      } else {
        console.warn(`[${id}] register 応答が想定外: ${JSON.stringify(res).slice(0, 200)}`);
        skipped++;
      }
    } catch (e) {
      const m = e.message ?? String(e);
      if (m.includes('already exists')) {
        console.log(`[${id}] 既に active project — skip (既存の .env credentials が有効である想定)`);
        skipped++;
      } else {
        console.error(`[${id}] register 失敗: ${m}`);
        failed++;
      }
    }
  }

  console.log(`\n[cernere-register] 完了: 登録=${registered}, reactivated=${reactivated}, skip=${skipped}, 失敗=${failed}`);
  if (registered > 0) {
    console.log(`各サービスの .env に CERNERE_* を書込済 — 即 dev で動きます (tsx が自動 load)`);
  }
  if (failed) process.exit(1);
}

// ── 通常 op (npm run env:<op>) ────────────────────────────────

/** 1 サービスで 1 op を実行。 失敗時 false。 */
function runEnvOp(spec, op, opArg) {
  const dir = resolve(ROOT, spec.repoDir, spec.subDir ?? '.');
  if (!existsSync(join(dir, 'package.json'))) {
    console.error(`[${spec.id}] package.json 不在 (${dir}) — skip`);
    return false;
  }
  console.log(`\n=== [${spec.id}] ${spec.displayName}  env:${op}${opArg ? ` ${opArg}` : ''} ===`);
  const args = ['run', `env:${op}`];
  if (opArg) args.push('--', opArg);
  const r = spawnSync('npm', args, { cwd: dir, stdio: 'inherit', shell: true });
  if (r.status !== 0) {
    console.error(`[${spec.id}] env:${op} 失敗 (exit ${r.status})`);
    return false;
  }
  return true;
}

function runNpmOp(op, opArg, rest) {
  const { ids, unknown } = resolveIds(rest, { requireEnvCli: rest.includes('--all') });
  if (unknown.length) {
    console.error(`unknown service IDs: ${unknown.join(', ')}`);
    process.exit(2);
  }
  if (!ids.length) {
    console.error('対象サービスがありません');
    printUsage();
    process.exit(2);
  }

  let failed = 0;
  for (const id of ids) {
    const spec = findService(id);
    if (!spec) continue;
    if (!spec.hasEnvCli) {
      console.warn(`[${id}] hasEnvCli=false — skip`);
      continue;
    }
    const ok = runEnvOp(spec, op, opArg);
    if (!ok) { failed++; continue; }

    // initialize は Infisical に defaults を登録するだけで .env を書かない。
    // この wrapper は initialize 直後に gen も回して .env を生成しておく
    // (= サービスの dev script が走る状態にする)。 standalone env-cli の
    // initialize とは behaviour が違うが、 「LUDIARS 一括 bootstrap」 として
    // よく使う流れなので統合する。
    if (op === 'initialize') {
      console.log(`[${id}] initialize 完了 — 続けて env:gen で .env を書込`);
      const genOk = runEnvOp(spec, 'gen', null);
      if (!genOk) failed++;
    }
  }

  if (failed) {
    console.error(`\n[infisical] ${failed}/${ids.length} サービスが失敗`);
    process.exit(1);
  }
  console.log(`\n[infisical] 完了 (${ids.length} サービス)`);
}

// ── main ──────────────────────────────────────────────────────

function main() {
  const argv = process.argv.slice(2);
  if (argv.includes('--help') || argv.length === 0) {
    printUsage();
    process.exit(argv.length === 0 ? 2 : 0);
  }

  const op = argv[0];
  if (!VALID_OPS.includes(op)) {
    console.error(`unknown op: ${op}`);
    printUsage();
    process.exit(2);
  }

  if (op === 'setup-batch') {
    runSetupBatch(argv.slice(1));
    return;
  }

  if (op === 'cernere-register') {
    runCernereRegister(argv.slice(1)).catch((e) => {
      console.error(e);
      process.exit(1);
    });
    return;
  }

  let opArg = null;
  let restStart = 1;
  if (op === 'get' || op === 'set') {
    opArg = argv[1] ?? null;
    restStart = 2;
    if (!opArg) {
      console.error(`${op} には key${op === 'set' ? '=value' : ''} 引数が必要です`);
      process.exit(2);
    }
  }
  runNpmOp(op, opArg, argv.slice(restStart));
}

main();
